default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: marvel_api_development

test:
  <<: *default
  database: marvel_api_test

production:
  <<: *default
  database: marvel_api_production
  username: marvel_api
  password: <%= ENV['MARVEL_API_DATABASE_PASSWORD'] %>
